addSbtPlugin("org.jetbrains"    % "sbt-ide-settings"       % "1.1.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"           % "2.4.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"    % "1.7.5")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"             % "4.1.1")
addSbtPlugin("au.com.onegeek"   % "sbt-dotenv"             % "2.1.204")
addSbtPlugin("io.gatling"       % "gatling-sbt"            % "3.2.2")
